version: '2'

volumes:
  # We'll define a volume that will store the data from the postgres databases:
  pg-data:
    driver: local

services:
  web:
    build: .
    volumes:
      - .:/usr/src
    ports:
      - 80:8080
    depends_on:
      - db
    command: yarn start
    environment:
      - DATABASE_URL=postgres://shit_tony_says:mysecretpassword@db:5432/shit_tony_says
      - PATH=$PATH:/usr/src/node_modules

  db:
    image: postgres:9.6
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: shit_tony_says

