version: '2'

volumes:
  # We'll define a volume that will store the data from the postgres databases:
  pg-data:
    driver: local

services:
  web:
    build: .
    volumes:
      - .:/usr/src
    ports:
      - 80:8080
    depends_on:
      - db
    command: yarn start
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
