version: '2'

services:
  web:
    build: .
    ports:
      - 80:8080
    links:
      - db
    command: yarn start
    environment:
      - DATABASE_URL=postgres://shit_tony_says:mysecretpassword@db/shit_tony_says
      - PATH=$PATH:/usr/src/app/node_modules
  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: shit_tony_says

